{
 "title": "Apps",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namepsace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods by Node",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (container_memory_working_set_bytes{pod!=\"\", namespace=~\"$namespace\", instance=~\"$node\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (rate(container_cpu_usage_seconds_total{pod!=\"\", namespace=~\"$namespace\", instance=~\"$node\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}