{
 "title": "PVE",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds{job=\"integrations/unix\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\"} / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max by(instance) (node_hwmon_temp_celsius{chip=~\"platform_coretemp_0|pci0000:00_0000:00:18_3\", instance=~\"$node\"})) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node\"} / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(max by(instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\", instance=~\"$node\"})) ",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$node\", chip=\"pci0000:00_0000:00:18_3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.*|overlay\", instance=~\"$node\", mountpoint!~\"|/boot/efi|/efi|.+nfs.+\"} / node_filesystem_size_bytes) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}